# Generated by Django 3.2.9 on 2021-11-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
    ]
