# Generated by Django 3.2.9 on 2021-11-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='NoCategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category'),
        ),
    ]
