# Generated by Django 3.2.9 on 2021-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_counter',
            field=models.IntegerField(default=0),
        ),
    ]
